import express from "express";
import { singleFile } from "../../Config/multerConfig.js";
import { addStore } from "./Controllers/addstore.controller.js";
import { getAllActiveStores, getAllStores, getOneStore, getStoresByCategory } from "./Controllers/getstore.controller.js";
import { editstore } from "./Controllers/editstore.controller.js";
import { deleteStore } from "./Controllers/deletestore.controller.js";
import { authorizeRoles, isAuthenticated } from "../../Middlewares/auth.middleware.js";
const router = express.Router();
router.post('/', isAuthenticated, authorizeRoles("admin"), singleFile("logo", "store"), addStore);
router.get('/', isAuthenticated, authorizeRoles("admin"), getAllStores);
router.get('/all', getAllActiveStores);
router.get('/:id', getOneStore);
router.get('/storebyslug/:slug', getStoresByCategory);
router.patch('/delete/:id', isAuthenticated, authorizeRoles("admin"), deleteStore);
router.patch('/:id', isAuthenticated, authorizeRoles("admin"), singleFile("logo", "store"), editstore);
export default router;